# Generated by Django 5.2.8 on 2025-11-10 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_uploadbatch_alter_imageitem_options_imageitem_lat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uploadbatch',
            options={},
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ui.uploadbatch'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='file',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(default='READY', max_length=20),
        ),
    ]
