# Generated by Django 5.2.8 on 2025-11-10 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_alter_imageitem_options_alter_uploadbatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ui.uploadbatch'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='file',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
