# Generated by Django 5.2.8 on 2025-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_alter_imageitem_batch_alter_imageitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='congestion',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='status',
            field=models.CharField(choices=[('OK', '정상'), ('BAD', '불량'), ('WAIT', '대기')], default='WAIT', max_length=10),
        ),
    ]
