# Generated by Django 5.2.8 on 2025-11-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_imageitem_congestion_alter_imageitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(choices=[('READY', '준비'), ('RUNNING', '진행중'), ('DONE', '완료')], default='READY', max_length=10),
        ),
    ]
