# Generated by Django 5.2.8 on 2025-11-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_alter_uploadbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(default='READY', help_text='READY / RUNNING / DONE 등 상태표시용', max_length=20),
        ),
    ]
