# Generated by Django 5.2.8 on 2025-11-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('defect_ratio_thr', models.FloatField(default=0.05, help_text='lane 내부에서 defect 비율이 이 값 이상이면 defect 처리')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
