# Generated by Django 5.2.8 on 2025-11-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_inferenceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('tmap_app_key', models.CharField(max_length=255, verbose_name='Tmap APP KEY')),
                ('ic_csv', models.FileField(blank=True, help_text='IC/JC 좌표가 들어있는 CSV 파일', null=True, upload_to='config/', verbose_name='IC/JC 목록 CSV')),
                ('hourly_csv', models.FileField(blank=True, help_text='영업소/집계시/교통량이 들어있는 CSV 파일', null=True, upload_to='config/', verbose_name='시간대별 교통량 CSV')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inferenceconfig',
            name='defect_ratio_thr',
            field=models.FloatField(default=0.05),
        ),
    ]
