# Generated by Django 5.2.8 on 2025-11-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_trafficconfig_alter_inferenceconfig_defect_ratio_thr'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(default='READY', help_text='배치 상태', max_length=20),
        ),
    ]
